703 feedback on tom swift module from swift operations team
TOMToolkit/tom_swift pull request #8
Opened 2023-10-31 18:50 UTC by phycodurus

the commits tell the tale :-)

2023-10-31 21:02 UTC, jchate6 requested changes
Is the 500s exposure time default from somewhere?
Is this a reasonable exposure time for a swift observation?

The monitoring frequency might benefit from additional help text. I think it should be more explicit if `monitoring_freq` = 2 and `monitoring_units`=hour means once every 2 hours or twice every hour.

2023-10-31 22:20 UTC, phycodurus commented on tom_swift/swift.py
> +        help_text=mark_safe((f'These are some common UVOT Filter modes.'
User may want to provide UVOT filter mode instructions even when using 0x9999. (Also, we may have more input from the Swift Ops team on how UVOT filter mode presented).

2023-11-01 21:32 UTC, jchate6 commented
@phycodurus Before release, should we remove the alpha release warning in the readme?

2023-11-01 22:32 UTC, jchate6 commented
Also you need to update the dependencies to require `tomtoolkit = "^2.15"`

2023-11-02 18:56 UTC, phycodurus commented on tom_swift/swift.py
>      # Exposure requested time (total)
yes

2023-11-03 19:57 UTC, jchate6 requested changes
Once I have values in the exposure time and exposure justification fields, I can hit validate and I get the following error: `Could not decode JWT, username/secret wrong?`

I'm pretty sure my swift credentials are accurate though.

2023-11-03 19:57 UTC, jchate6 commented on tom_swift/swift.py
> +        required=True,
I think there's an issue here when this field is hidden and blank that causes an error when trying to validate:
`An invalid form control with name='exposure' is not focusable. <input type=​"number" name=​"exposure" value=​"12" step=​"any" class=​"numberinput form-control" required id=​"id_exposure">​
`

2023-11-03 19:57 UTC, jchate6 commented on tom_swift/swift.py
> +        required=True,
This has the same issue as Total Exposure time above.

2023-11-03 19:58 UTC, jchate6 commented on tom_swift/swift.py
> +        required=True,
This error is invisible unless the console is open and just looks like nothing happens when you try to validate.

2023-12-20 02:41 UTC, jchate6 commented
I'm experiencing the same `Could not decode JWT, username/secret wrong?` Is the Username different from the one I use to log into www.swift.psu.edu?

2023-12-20 17:59 UTC, jchate6 commented
I have even tried making a new set of credentials.

2023-12-20 23:43 UTC, jchate6 approved these changes
Figured it out. I was still using `SWIFT_PASSWORD` from an earlier version.

2023-12-22 21:51 UTC, merged